name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6d4559418a2e2372cafab86cb1b710b707d56626446ae956ffc32a4bbe10756"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
