name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70000d73db9865e077afd6a2cde895bfce9233aef258972fd84e90c2035c05c8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
