name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e442ee176ac0700bc57f2288c5f15986ec0237c931f15a786b06b4660f61eb7c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
