name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "253d0d6ef908979d62308eff0f59c715edc77fbfe524212a35b0a232c51faf58"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
