name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce102e55eb6f97f7c95bded23d43eb22de224cefea98cb6342d7f9f2f6fdb968"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
