name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ce515d2cd31af7620eef509158072f8455bc2e95ded96fa74f3abcbcd0c03a0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
