name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "120edf1083dea446edfe757096dfb0caf84d4efcd23787d0809e48fb99610f6f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
