name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed8db3440148dddcadb1e66bcac6d003a7a1ad70ebdca1bf5df5002dafc4fa18"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
